# Generated by Django 5.0.6 on 2024-08-26 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_comment_listing_listingcategories_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='byUser',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='imgURL',
            field=models.URLField(blank=True, default=''),
        ),
    ]
