# Generated by Django 5.0.6 on 2024-08-29 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_byuser_alter_listing_imgurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='startingPrice',
            new_name='starting_price',
        ),
    ]
