# Generated by Django 5.0.6 on 2024-09-02 06:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_startingprice_listing_starting_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlisted_by',
            field=models.ManyToManyField(related_name='watchlist_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
