# Generated by Django 5.0.6 on 2024-09-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('CLO', 'Closed')], default='ACT', max_length=10),
        ),
    ]
